//#include "all_features.h"

#define FEATURE_CROP_MODE_HACK
#define FEATURE_AUDIO_REMOTE_SHOT

#define FEATURE_FLEXINFO

#define FEATURE_DONT_CLICK_ME
#define FEATURE_SHOW_SHUTTER_COUNT
#define FEATURE_SHOW_FREE_MEMORY
#define FEATURE_SCREENSHOT

#define CONFIG_LIVEVIEW

// Mostly working - task display is too crowded.
#define CONFIG_TSKMON
#define FEATURE_SHOW_TASKS
#define FEATURE_SHOW_CPU_USAGE
#define FEATURE_SHOW_GUI_EVENTS

#define FEATURE_INTERVALOMETER

// enable global draw
#define FEATURE_GLOBAL_DRAW
#define FEATURE_CROPMARKS

// Needs testing, hopefully works
#define CONFIG_CRASH_LOG

#undef CONFIG_ADDITIONAL_VERSION
#undef CONFIG_AUTOBACKUP_ROM

#undef CONFIG_PROP_REQUEST_CHANGE
